name: Create a test build

permissions:
  contents: write

on:
  pull_request:
  push:
    branches:
      - '!stable'
      - '!develop'

jobs:
  package_multiplatform:
    name: 'Create a test build'
    uses: ./.github/workflows/job_build_game.yml
    secrets: inherit

  package_mac:
    name: 'Create a test build (macOS)'
    if: vars.MACOS_ENABLE == 'true'
    uses: ./.github/workflows/job_build_game_macos.yml
    with:
      let_mac_fail: true
    secrets: inherit
